### ISSUE TITLE
PCMBase crashes on debian-clang

### ISSUE THREAD

**Issue by krzbar** [venelin/PCMBase#4] opened 2019-12-10 11:11 UTC
PCMBasecrashes on r-devel-linux-x86_64-debian-clang
( https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-clang/PCMBase-00check.html ) Is it known what the crash is due to and how is it with the possibilites of fixing it? 
Thanks
Krzysztof

**Comment by venelin** [comment] 2020-02-15 13:43
This issue has been discussed offline and since the problem is due to an unresolvable compiler incompatibility of the PCMBaseCpp package, I'm closing this issue here.

**Closed by venelin** 2020-02-15 13:43 UTC
